version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trent
    ports: ["5432:5432"]
    healthcheck: { test: ["CMD", "pg_isready", "-U", "postgres"], interval: 5s, timeout: 5s, retries: 20 }


  redis:
    image: redis:7
    ports: ["6379:6379"]


  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000", "9001:9001"]


  backend:
    build: ./backend
    env_file: .env
    depends_on: [db, redis, minio]
    ports: ["8000:8000"]


  worker:
    build: ./backend
    command: sh -c "celery -A celery_worker.celery worker -l info"
    env_file: .env
    depends_on: [backend]


  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:8000
    ports: ["5173:5173"]
    depends_on: [backend]